default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: pguser
  password: mindfire

development:
  <<: *default
  database: location_sharing

test:
  <<: *default
  database: location_sharing_test

production:
  <<: *default
  database: location_sharing_prod

